objects:
  - name: any_targets|0
    expr_type: movable_entity_type
  - name: TARGET_any_targets|0
    expr_type: goal_entity_type
  - name: any_targets|1
    expr_type: movable_entity_type
  - name: TARGET_any_targets|1
    expr_type: goal_entity_type
  - name: any_targets|2
    expr_type: movable_entity_type
  - name: TARGET_any_targets|2
    expr_type: goal_entity_type
  - name: any_targets|3
    expr_type: movable_entity_type
  - name: TARGET_any_targets|3
    expr_type: goal_entity_type
  - name: robot_0
    expr_type: robot_entity_type
  - name: robot_1
    expr_type: robot_entity_type

goal:
  expr_type: AND
  sub_exprs:
    - at(any_targets|1,TARGET_any_targets|1)
    - at(any_targets|2,TARGET_any_targets|2)
    - at(any_targets|3,TARGET_any_targets|3)
    - not_holding(robot_0)
    - not_holding(robot_1)

stage_goals:
  stage_1:
    expr_type: AND
    sub_exprs:
      - at(any_targets|1,TARGET_any_targets|1)
  stage_2:
    expr_type: AND
    sub_exprs:
      - at(any_targets|1,TARGET_any_targets|1)
      - at(any_targets|3,TARGET_any_targets|3)
  stage_3:
    expr_type: AND
    sub_exprs:
      - at(any_targets|1,TARGET_any_targets|1)
      - at(any_targets|3,TARGET_any_targets|3)
      - at(any_targets|2,TARGET_any_targets|2)

solution:
  - nav_to_goal(any_targets|0, robot_0)
  #- pick(any_targets|0, robot_0)
  - nav_to_obj(TARGET_any_targets|0, robot_0)
  #- place(any_targets|0,TARGET_any_targets|0, robot_0)
  - nav_to_goal(any_targets|1, robot_1)
  - pick(any_targets|1, robot_1)
  - nav_to_obj(TARGET_any_targets|1, robot_1)
  - place(any_targets|1,TARGET_any_targets|1, robot_1)
  - nav_to_goal(any_targets|2, robot_0)
  - pick(any_targets|2, robot_0)
  - nav_to_obj(TARGET_any_targets|2, robot_0)
  - place(any_targets|2,TARGET_any_targets|2, robot_0)
  - nav_to_goal(any_targets|3, robot_1)
  - pick(any_targets|3, robot_1)
  - nav_to_obj(TARGET_any_targets|3, robot_1)
  - place(any_targets|3,TARGET_any_targets|3, robot_1)

